### ISSUE TITLE
Handle missing data in forcings

### ISSUE THREAD

**Issue by kandread** [nasa/RHEAS#100]

**Comment by samburu** [comment]
When i adopt the above commit i get the following error:
`psycopg2.ProgrammingError: relation "precip.ncep" does not exist
LINE 1: ...as x, st_worldtorastercoordy(rast,geom) as y from precip.nce...
`
I tried to solve the issue by making the following changes:
`tmax = self._handleMissingData(tmax, "tmax.{0}".format(self.temp)) #replace "precip.{0}" with  "tmax.{0}"`

`tmin = self._handleMissingData(tmin, "tmin.{0}".format(self.temp)) #replace "precip.{0}" with  "tmin.{0}"`

`wind = self._handleMissingData(wind, "wind.{0}".format(self.wind)) #replace "precip.{0}" with  "wind.{0}"`

But then i get the following error:
`IOError: File ./tmpxA91Ee/output/wb_3.625_30.625 does not exist`

**Comment by kandread** [comment]
This should be fixed with a1952703bcc39c7489fb4bdcf63e4235e01425e3 
We are testing a a bit more, but will merge to the `master` branch soon. Switch to the `develop` branch if you need this now.

**Comment by samburu** [comment]
When i switch to `develop` do i've to repeat the following steps:

- `python bootstrap.py`

- `./bin/buildout`

**Comment by kandread** [comment]
Nope. Just do 
`./bin/buildout install paths` to be safe

**Comment by samburu** [comment]
After switching to `develop` I'm getting this warning
`IOError: File ./tmp7y8kKs/output/wb_3.625_30.625 does not exist`
is there a minimum number of year of data required to do a forecast?
