### ISSUE TITLE
Error: Referenced option does not exist: environment EARTHDATA_USER when running

### ISSUE THREAD

**Issue by samburu** [nasa/RHEAS#103]
Error: Referenced option does not exist: environment EARTHDATA_USER when running `./bin/buildout`

**Comment by samburu** [comment]
replaced `${environment:EARTHDATA_USER}` with Earthdata username and `${environment:EARTHDATA_PASSWORD}` with password

**Comment by kandread** [comment]
Another way that this can be fixed is if you set the environment variables before running the `buildout` script
`export EARTHDATA_USER=username`
`export EARTHDATA_PASSWORD=password`

**Comment by samburu** [comment]
Thanks with `export` I don't have to expose the login details safe
