### ISSUE TITLE
conda package for installing RHEAS

### ISSUE THREAD

**Issue by KMarkert** [nasa/RHEAS#111]
Would it be possible to have a conda package through conda-forge for installing RHEAS? It would help with the package management and postgres. It would be nice to have this so that we can use the conda environment manager for RHEAS and its dependencies.

**Comment by kandread** [comment]
Should be possible although it looks a bit more involved than a simple implementation. Don't have any experience with conda recipes though so I might be off.

**Comment by nndas** [comment]
Resolved.
