### ISSUE TITLE
RHEAS installing on macOS Sierra 10.12.6 - Error: Referenced option does not exist: environment EARTHDATA_USER

### ISSUE THREAD

**Issue by giaMSU** [nasa/RHEAS#128]
I got an error when buildout the RHEAS. Please help me to solve it.
Thanks

_GIAs-MBP:RHEAS GIANGUYEN$ ./bin/buildout
Develop: '/Users/GIANGUYEN/RHEAS/.'
While:
  Installing.
  Getting section earthdata.
  Initializing section earthdata.
  Getting option earthdata:cmds.
Error: Referenced option does not exist: environment EARTHDATA_USER_

**Comment by kandread** [comment]
You need to create a NASA Earthdata account and then set the options with

`export EARTHDATA_USER=username`
`export EARTHDATA_PASSWORD=password`

before running `buildout`

**Comment by giaMSU** [comment]
Thank you so much!
