### ISSUE TITLE
Nowcast running error

### ISSUE THREAD

**Issue by akssinghe** [nasa/RHEAS#26]
Hi Kostas,
## I got the below error when running a nowcast for a month period with 0.25 res.

Traceback (most recent call last):
  File "./rheas", line 17, in <module>
    sys.exit(rheas.run())
  File "/home/susantha/RHEAS/src/rheas.py", line 81, in run
    nowcast.execute(dbname, options)
  File "/home/susantha/RHEAS/src/nowcast.py", line 187, in execute
    runVIC(dbname, options)
  File "/home/susantha/RHEAS/src/nowcast.py", line 29, in runVIC
    runDeterministicVIC(dbname, options)
  File "/home/susantha/RHEAS/src/nowcast.py", line 76, in runDeterministicVIC
    model.writeForcings(prec, tmax, tmin, wind)
  File "/home/susantha/RHEAS/src/vic/vic.py", line 380, in writeForcings
##     tmin) == len(self.lat) \* ndays and len(wind) == len(self.lat) \* ndays

when I count the days for precip.trmm table is 30. 
But precip.trmm_4 table is also 30. As I know it should be 120 (30*4)

there is no issue for temp and wind.

pls let me know your ideas to sort this out.

Best!

**Comment by kandread** [comment]
hi Susantha,

the number in trim_4 refers to the resolution (1/4 is 0.25 degrees etc.) so you won't have 30*4 rows necessarily. The error you're getting means that you probably have a corrupted database. Are you running the test basin?
If so, can you run this in the psql shell?

select fdate,st_value(rast,geom) from precip.trmm_4,basin.basin where st_intersects(last,geom);

and see how many values you get?

**Comment by akssinghe** [comment]
Hi Kostas,

Since I was traveling in Cambodia during last couple of days, I was not able to engage with  RHEAS testing. 

BTW, when I invoke the command you provided, I am not getting any value. it is just shown 0 rows.

Anyway, pls just let me know, if database has been corrupted, do I need to install RHEAS again? or is there any method to repair it? 

Best,
Susantha

**Comment by kandread** [comment]
that explains the assertion error. I would say the best way is to probably rebuild the database with `./rheas -u data.conf`, and pulling some of the rasters in QGIS to see if everything looks right.
