### ISSUE TITLE
smdi equation

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#27]
K, Could you double-check the smdi equation? The results are way too low (orders of magnitude) for every date I've viewed, compared to the examples I'm seeing in papers. Thanks! A

Example: http://i.imgur.com/zOtBAEn.png

**Comment by AdamJDuncan** [comment]
ps: on Tues you mentioned we should label issues to keep things organized... I don't have those privileges.

**Comment by AdamJDuncan** [comment]
That example is entire region, Feb 28 2016... 14 months into the nowcast. CMORPH/NCEP/0.25.

**Comment by kandread** [comment]
Although these are not unreasonable values, there was a bug in the SMDI calculation (should be fixed with 80404b62cb51887437ebf7dc60c4bc441b73acfa).

**Comment by AdamJDuncan** [comment]
This appears to be fixed, thank you.
