### ISSUE TITLE
sri equation

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#30]
OK first off, SPI is fine.

SRI may be, but every time length (1 month, 3 month, etc), throughout the 14-month nowcast, gets negative infinite values for a couple pixels. Oddly, the location of these pixels change for different time lengths... but all occur in a mountainous region in Yunnan. I can just cut it out, but still...  an example centroid is 24.125, 100.375. 

I'm assuming these are pixels surrounded by higher elevations?

Example: http://i.imgur.com/Ygdnl38.png

**Comment by kandread** [comment]
Can you try it after applying c4a9117e3a1d098e193b30e29536b875f82e112c ?

**Comment by AdamJDuncan** [comment]
This fixed the issue, thank you.
