### ISSUE TITLE
Ensembles overwriting the former?

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#38]
I've run a hindcast on a tributary basin with five ensembles. I expected there would be five outputs for each date. Instead there's only one, all classified as "5" under ensemble. I was expecting to just run 20 ensembles on, say, SMDI, and using the different outputs, classify each pixel as percentile chance of it having a score below -2 next month. Instead the last ensemble has overwritten all the others. Does each ensemble increase the accuracy of the next, so the last is all we need? I thought each ensemble was independent of the others, each fed slightly different initial conditions.

**Comment by AdamJDuncan** [comment]
*percentage chance

Or is it just the average?

**Comment by kandread** [comment]
Can you test it with a7a621073ac156f3d3a765616bf59139bb17b003?
