### ISSUE TITLE
Ingestion of vic.soils in rheas database

### ISSUE THREAD

**Issue by nndas** [nasa/RHEAS#4]
Please look into this matter. During buildout the vic.soils data is not getting ingested due to role associated with it, it always come up as, "the kandread role does not exist" and then discontinue the vic.soils ingestion into the rheas database. However, when done separately after buildout, the vic.soils data is successfully ingested.

**Comment by kandread** [comment]
That is a warning, shouldn't affect installation. Closing issue.
