### ISSUE TITLE
CHIRPS downloading monthly sums, not daily.

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#40]
Here's a selection from a histogram showing precip (mm) frequency from a CMORPH multiband raster, with each band representing an individual date, July 1 - 31 2015: http://i.imgur.com/paS2T7V.png

Here's the same for CHIRPS: http://i.imgur.com/Pu87XGb.png

It appears the first of each month (Band 1) is a monthly sum, and the rest of the dates (all obfuscated by Band 31) are empty (notwithstanding an error in Yunnan).

I've double-checked by creating individual tables for certain dates and it's a pattern.

This could be an issue on their end.

**Comment by kandread** [comment]
Not sure but 5e935e09b5f69b136db7bfffa42cb2423e598343 might fix this issue.

**Comment by AdamJDuncan** [comment]
We'd modified the script with a url Susantha had found, but I've tried this update on a 15-day period and it also appears to have fixed the issue, thank you. Closing.

http://i.imgur.com/0DmZZiU.png
