### ISSUE TITLE
DSSAT completion 

### ISSUE THREAD

**Issue by vks01** [nasa/RHEAS#51]
I am trying to run a DSSAT nowcast using the sample files. When I run a nowcast for the 2013 growing season (start and end dates from Feb - September, 2013) using CHIRPS and NCEP as input, the model runs through to completion. However, if I try to run any other year (I tried 2001, 2005, 2009, 2010, 2011, 2012 and 2014, using the same start and end dates as 2013), I get one of 3 different situations depending on the year:
1. the model terminates at different plant growth stages with an error that says 'Crop failure growth program terminated'
   Or,
2. The program runs through to different crop growth stages (without reaching harvest) and says 'RUN COMPLETE, SAVING....'. But the model appears to have terminated way before reaching harvest. 
   Or,
3. I get an error "forrtl: severe (64): input conversion error, unit -5, file Internal Formatted Read"
   I get the third error regardless of year when I try to run a forecast. 

Also, does the DSSAT nowcast/forecast save the output to the same database? I dont see any of the 2013 results in the rheas database. Does the save option have to be explicitly defined in the nowcast.conf under the dssat parameters (I have a save: db listed under vic, as outlined in the example).

**Comment by nndas** [comment]
Resolved.
