### ISSUE TITLE
CMORPH specific date issues

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#53]
I'm having issues with CMORPH for two specific dates: 2009-04-01 & 2013-04-23. The tables ARE populated with rasters that I can see numerically but do not appear in qgis with

```
create table xxxx.xxxx as (select rid, raster from precip.cmorph where fdate: 'xxxx-xx-xx')
```

Unlike all other dates. Multiple tries do nothing. Corrupted at source, maybe? I don't think this used to be an issue. Means that running the following nowcast requires manual editing of the rasters for those certain dates. Maybe nodata can be set as 0 in this sort of case? Regards.

```
[nowcast]
model: vic
startdate: 2013-04-20
enddate: 2013-04-25
name: Test_GapFinding
basin:/home/ubuntu14/RHEAS/bin/bbox/BBox_Cambo.shp
resolution: 0.25

[vic]
precip: cmorph
temperature: ncep
wind: ncep
save to: db
save: rainf
initialize: off

```

(Area is subset of Lower Mekong Region, which is:)

```
minlat: 5.5
maxlat: 28.75
minlon: 92.0
maxlon: 109.75
```

**Comment by kandread** [comment]
Finally got around to this. There still is an upstream issue (missing data) so nothing to do with RHEAS. I'm inclined not to introduce zero precipitation days, so I'll let the run exit with the "Missing meteorological data" message. Closing but feel free to reopen. Best!
