### ISSUE TITLE
Check SMOS data over ocean

### ISSUE THREAD

**Issue by kandread** [nasa/RHEAS#57]
Weird artifact over ocean in SMOS data.

**Comment by akssinghe** [comment]
Could this be a geo-referenced issue of the data set? If we look at the data set through NASA Worldview (https://worldview.earthdata.nasa.gov), it shows in proper way. Attached image is depicted how much has shifted the data from its origin when look through RHEAS (derived for 2010-03-01). 
![smos_20100301](https://user-images.githubusercontent.com/18065536/28703185-86d237ae-738c-11e7-94c5-7a4056e2fabc.JPG)

**Comment by Hungpham02015** [comment]
Dear Prof. Kostas Andreadis. I am Hung from Vietnamese Academia for Water Resources (VAWR) in last year you have visited for training course on RHEAS. I think RHEAS  is very important for water resources in Vietnam. Now we are appling RHEAS in some area in our country. But we have some problems with RHEAS : 
1. We can not import DATA from SMOS for assimilation. I think the http of smos maybe changed. Can you give us the address of the http of smos.
2. When we use the forecast we use the method esp but there is error : Attribute "map" has not function " remove"  ? can you help us.
3. Can you explain to us how to run the DSSAT in detail.
Thank you very much. We hope the cooperation between your department and VAWR will develop in future. I hope to see you one more in Ha noi.
Best Regards,
Pham Hung
