### ISSUE TITLE
RHEAS and DSSAT on Mac

### ISSUE THREAD

**Issue by Mohgli** [nasa/RHEAS#68]
Hi

To my knowledge DSSAT currently is only available on Windows. However it seems that RHEAS does not really work on Windows due to backward compatibility issues. Hence I am wondering how I can run RHEAS on Mac while I cannot have DSSAT (at least not straight forward installation) run on Mac.

My apologies if this is a dumb question.

**Comment by kandread** [comment]
Hi,

we use [Wine](https://www.winehq.org/) which allows running (some) Windows applications on Unix-like systems. Theoretically, you should be able to use it outside of RHEAS to run your version of DSSAT but I haven't tested that. You should be able to install RHEAS on a Mac, following the [instructions](http://rheas.readthedocs.io/en/latest/installation.html#installing-on-linux-and-macos).
