### ISSUE TITLE
LAI Data Saving Issue

### ISSUE THREAD

**Issue by akssinghe** [nasa/RHEAS#75]
Even though LAI data successfully fetching into db, but LAI schema is empty.

**Comment by kandread** [comment]
Can you paste your config file here?

**Comment by akssinghe** [comment]
[domain]
minlat: 5.5
maxlat: 28.75
minlon: 92.0
maxlon: 109.75

[mcd15]
startdate: 2010-1-1
enddate: 2010-1-30

**Comment by kandread** [comment]
I cannot reproduce this. It must be something on your end. After running this, I get the following rasters in the database

`rheas=# select fdate from lai.modis;
   fdate
------------
 2010-01-01
 2010-01-09
 2010-01-17
 2010-01-25
(4 rows)`

Closing this, let's debug it on your machine.
