### ISSUE TITLE
CHIRPS download failing after 1 day

### ISSUE THREAD

**Issue by wle0001** [nasa/RHEAS#83]
Installed a new instance of RHEAS and can't get CHIRPS to download. Stops after the first table has been imported. 

INFO: Imported 2016-01-01 in precip.chirps
WARNING: No data were available to import into precip.chirps for 2016-01-02.
WARNING: No data were available to import into precip.chirps for 2016-01-03.

Traced it to the http decorator lfilename exception I believe, but can't figure out why it won't download the second request. The data is there and can be downloaded. If the data request spans multiple years, the Jan 1 file will again download but says their is no data for  the second or any after. 

Log file 

[chirpsLog.log](https://github.com/nasa/RHEAS/files/1522040/chirpsLog.log)

**Comment by kandread** [comment]
Are you using the latest master? I encountered this too, was a weird one to figure out. It's fixed by fd0292e070a20b178ead79509e4aeedd5e29d36c. That reminds me, I need to merge the updates to the support/servir branch.
