### ISSUE TITLE
Problem ingesting LAI for running DSSAT

### ISSUE THREAD

**Issue by SarvaPulla** [nasa/RHEAS#89]
Every time you run DSSAT the output yield is being returned as 0. This might be caused due to the fact that LAI is not being ingested into the database. After running the buildout.cfg file there is no lai.modis table in the lai shcema. When you run a data.conf file with the following paramters.

[domain]
minlat: 34.10
maxlat: 37.25
minlon: -88.70
maxlon: -81.25

[mcd15]
startdate: 2015-1-1
enddate: 2015-12-31

It's throwing the following error:
WARNING: Missing options for local dataset mcd15. Nothing ingested!

**Comment by kandread** [comment]
Regarding the LAI issue, you're probably missing the `lxml` and/or `requests` modules.
Can you try running 
`pip install lxml requests`
However, there's a larger issue since NASA switched these data to an HTPPS login which leads to an authentication error.

**Comment by SarvaPulla** [comment]
After installing the lxml and requests it's not throwing the missing options error. But now as expected it's saying that there is no data available for that time.
