### ISSUE TITLE
[trmm] requires end date?

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#9]
[trmm] gives a net-cdf error if I try to fetch anything after Dec 31 2015. Maybe it should instruct the user to specify/move the end date.

**Comment by AdamJDuncan** [comment]
Ian has informed me that it died... well there you go.

**Comment by kandread** [comment]
TRMM has stopped producing data (see mission update at http://pmm.nasa.gov/trmm). I'll add an exception that prints out a warning.
