### ISSUE TITLE
Error when updating database

### ISSUE THREAD

**Issue by VuPhuongNam** [nasa/RHEAS#94]
I have a error when I updating the database:

root@91c33d4e4aa5:/rheas# ./bin/rheas -u /data/data.conf 
INFO: Updating database!
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: <!DOCTYPE^ html><html lang="en-US" class="no-js"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width" /><title>Barcelona Expert Center | Maintenance tasks</title><link rel="profile" href="http://gmpg.org/xfn/11" /><link rel="pingback" href="http://bec.icm.csic.es/xmlrpc.php" /><link rel="alternate" type="application/rss+xml" title="Barcelona Expert Center &raquo; Feed" href="http://bec.icm.csic.es/feed/" /><link rel="alternate" type="application/rss+xml" title="Barcelona Expert Center &raquo; Comments Feed" href="http://bec.icm.csic.es/comments/feed/" /> <script type="text/javascript">//<![CDATA[ // Google Analytics for WordPress by Yoast v4.3.3 | http://yoast.com/wordpress/google-analytics/ var _gaq = _gaq || [];  var pluginUrl = '//www.google-analytics.com/plugins/ga/inpage_linkid.js'; _gaq.push(['_require', 'inpage_linkid', pluginUrl]); _gaq.push(['_setAccount', 'UA-41391196-1']);     _gaq.push(['_setCustomVar',1,'post_type','page',3],['_setCustomVar',2,'author','master',3],['_trackPageview']); (function () { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })(); //]]></script>     <script type="text/javascript">   window._wpemojiSettings = {"baseUrl":"http:\/\/s.w.org\/images\/core\/emoji\/72x72\/","ext":".png","source":{"concatemoji":"http:\/\/bec.icm.csic.es\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.2.4"}};   !function(a,b,c){function d(a){var c=b.createElement("canvas"),d=c.getContext&&c.getContext("2d");return d&&d.fillText?(d.textBaseline="top",d.font="600 32px Arial","flag"===a?(d.fillText(String.fromCharCode(55356,56812,55356,56807),0,0),c.toDataURL().length>3e3):(d.fillText(String.fromCharCode(55357,56835),0,0),0!==d.getImageData(16,16,1,1).data[0])):!1}function e(a){var c=b.createElement("script");c.src=a,c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var f,g;c.supports={simple:d("simple"),flag:d("flag")},c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.simple&&c.supports.flag||(g=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",g,!1),a.addEventListener("load",g,!1)):(a.attachEvent("onload",g),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),f=c.source||{},f.concatemoji?e(f.concatemoji):f.wpemoji&&f.twemoji&&(e(f.twemoji),e(f.wpemoji)))}(window,document,window._wpemojiSettings);  </script>  <style type="text/css">img.wp-smiley,img.emoji { display: inline !important; border: none !important; box-shadow: none !important; height: 1em !important; width: 1em !important; margin: 0 .07em !important; vertical-align: -0.1em !important; background: none !important; padding: 0 !important;}</style><link rel='stylesheet' id='sfw-comment-style-css' href='http://bec.icm.csic.es/wp-content/plugins/spam-free-wordpress/css/sfw-comment-style.css?1356224062' type='text/css' media='all' /><link rel='stylesheet' id='onlinemarketer_style-css' href='http://bec.icm.csic.es/wp-content/themes/online-marketer/style.css?ver=4.2.4' type='text/css' media='all' /><script type='text/javascript' src='http://bec.icm.csic.es/wp-includes/js/jquery/jquery.js?ver=1.11.2'></script><script type='text/javascript' src='http://bec.icm.csic.es/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.2.1'></script><script type='text/javascript' src='http://bec.icm.csic.es/wp-content/themes/online-marketer/library/js/modernizr-2.6.1.min.js?ver=2.6.1'></script><script type='text/javascript' src='http://bec.icm.csic.es/wp-content/themes/online-marketer/library/js/scripts.js?ver=1.0.0'></script><link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://bec.icm.csic.es/xmlrpc.php?rsd" /><link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://bec.icm.csic.es/wp-includes/wlwmanifest.xml" /> <meta name="generator" content="WordPress 4.2.4" /><link rel='canonical' href='http://bec.icm.csic.es/maintenance-tasks/' /><link rel='shortlink' href='http://bec.icm.csic.es/?p=2998' /><script type="text/javascript">/* <![CDATA[ */ jQuery.post("https://bec.icm.csic.es/wp-admin/admin-ajax.php", { action: "wmp_update", id: 2998, token: "9c1b9fe328" }); /* ]]> */</script><script type="text/javascript" src="http://bec.icm.csic.es/wp-content/plugins/wp-showhide-elements/wp-showhide-elements.js"></script></head><body class="page page-id-2998 page-template-default"><div id="container"> <header id="branding" role="banner">  <div id="inner-header" class="clearfix">  <hgroup id="top-header">   <div id="site-title"><a href="http://bec.icm.csic.es/" title="Barcelona Expert Center" rel="home">Barcelona Expert Center</a></div>   <div id="site-description">Remote sensing research, data distribution and visualization services</div>  </hgroup>  <form role="search" method="get" id="searchform" class="searchform" action="http://bec.icm.csic.es/">    <div>     <label class="screen-reader-text" for="s">Search for:</label>     <input type="text" value="" name="s" id="s" />     <input type="submit" id="searchsubmit" value="Search" />    </div>   </form>  <nav id="access" role="navigation">   <h1 class="assistive-text section-heading">Main menu</h1>   <div class="skip-link screen-reader-text"><a href="#content" title="Skip to content">Skip to content</a></div>   <div class="menu"><ul id="menu-main-menu" class="menu"><li id="menu-item-20" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="/">Home</a></li><li id="menu-item-19" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-19"><a href="http://bec.icm.csic.es/data/" >BEC Products</a><ul class="sub-menu"> <li id="menu-item-51" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-51"><a href="http://bec.icm.csic.es/data/available-products/" >Available variables</a> <ul class="sub-menu">  <li id="menu-item-2714" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2714"><a href="http://bec.icm.csic.es/ocean-datasets/" >Sea Surface Salinity</a></li>  <li id="menu-item-775" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-775"><a href="http://bec.icm.csic.es/ocean-auxiliary-dataset/" >Singularity Exponents</a></li>  <li id="menu-item-764" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-764"><a href="http://bec.icm.csic.es/land-datasets/" >Land Datasets</a></li> </ul></li> <li id="menu-item-62" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-62"><a href="http://bec.icm.csic.es/data/data-access/" >Data Access</a></li> <li id="menu-item-63" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63"><a href="http://bec.icm.csic.es/data/browse-maps/" >Browse Maps</a></li> <li id="menu-item-768" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-768"><a href="http://bec.icm.csic.es/products-documentation/" >Products Documentation</a></li> <li id="menu-item-1919" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1919"><a href="http://bec.icm.csic.es/data/singularity-analysis-service/" >Singularity Analysis Service</a></li></ul></li><li id="menu-item-2852" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-2852"><a href="/remote-sensing-special-issue">Remote Sensing Special Issue</a></li><li id="menu-item-91" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-91"><a href="http://bec.icm.csic.es/contact/" >Contact</a></li><li id="menu-item-45" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-45"><a href="http://bec.icm.csic.es/bec/" >About BEC</a></li></ul></div>  </nav> <div class="navbreak"></div> </div>    <div id="headerimg"><img src="http://bec.icm.csic.es/wp-content/themes/online-marketer/library/images/headers/logobec_975_96ppp.png" width="975" height="241" alt="" /></div>   </header>  <div id="content" class="clearfix">       <div id="main" class="col620 clearfix" role="main">         <header class="entry-header page-header">  <h1 class="entry-title">Maintenance tasks</h1></header><article id="post-2998" class="post-2998 page type-page status-publish hentry">  <div class="entry-content post_content">  <h3>The service you were looking for is unavailable due to maintenance tasks until May 28.</h3><h3>Sorry for the inconveniences.</h3>   </div> </article>                        </div>        <div id="secondary" class="sidebar col300" role="complementary">      <aside id="text-11" class="widget widget_text"><div class="widget-title">Maintenance tasks</div>   <div class="textwidget"><img class="alignleft size-full" src="http://bec.icm.csic.es/wp-content/uploads/2013/09/stop.png" width=90 border=0> Due to maintenance tasks, the access to data distribution service and maps server service will be stopped until next monday 28.</div>  </aside><aside id="text-3" class="widget widget_text"><div class="widget-title">Remote Sensing Special Issue</div>   <div class="textwidget"><table><tr><td><P align=justify>The Remote Sensing Journal and BEC have organized a Special Issue entitled "<em>Ten Years of Remote Sensing at Barcelona Expert Center</em>".</P></td><td>&nbsp;</td><td><a href="http://bec.icm.csic.es/remote-sensing-special-issue/" ><img src="http://bec.icm.csic.es/wp-content/uploads/2018/04/deadline.png" alt="deadline" width="75" height="75" /></a> </td></tr></table><div align="right"><a href="http://bec.icm.csic.es/remote-sensing-special-issue/" >Read more..</a></div></div>  </aside><aside id="text-5" class="widget widget_text"><div class="widget-title">Private zone</div>   <div class="textwidget"><ul class="sub-menu"> <li id="menu-item-51" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-51"><a href="/permissions/loginUser.zul" target="_blank">Modify your data</a></li><li id="menu-item-51" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-51"><a href="/permissions/loginUser.zul?action=remove" target="_blank">Delete your data</a></li><li id="menu-item-51" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-51"><a href="/permissions/" target="_blank">I forgot my password</a></li> <li id="menu-item-62" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-57 current_page_item menu-item-62"><a href="/data/data-access/#formdata">Register</a></li> </ul></div>  </aside><aside id="nav_menu-3" class="widget widget_nav_menu"><div class="widget-title">Our products</div><div class="menu-lateral-container"><ul id="menu-lateral" class="menu"><li id="menu-item-84" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-84"><a href="http://bec.icm.csic.es/data/available-products/" >Available Products</a></li><li id="menu-item-82" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-82"><a href="http://bec.icm.csic.es/data/data-access/" >Data Access</a></li><li id="menu-item-83" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-83"><a href="http://bec.icm.csic.es/data/browse-maps/" >Browse Maps</a></li><li id="menu-item-1918" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1918"><a href="http://bec.icm.csic.es/data/singularity-analysis-service/" >Singularity Analysis Service</a></li></ul></div></aside><aside id="text-10" class="widget widget_text"><div class="widget-title">Tweets by @BECICMRS</div>   <div class="textwidget"><a class="twitter-timeline" href="https://twitter.com/BECICMRS" onclick="javascript:_gaq.push(['_trackEvent','outbound-widget','http://twitter.com']);">Tweets by BECICMRS</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script><a class="twitter-follow-button" href="https://twitter.com/BECICMRS" data-size="large">Follow @BECICMRS</a></div>  </aside><aside id="wmp_widget-2" class="widget widget_wmp_widget"><div class="widget-title">Last month&#039;s most popular posts </div><ul>   <li><a href="http://bec.icm.csic.es/nodal-sampling-removing-tails-and-ripples-from-smos-brightness-temperatures/" title="Nodal sampling: removing tails and ripples from SMOS Brightness Temperatures">Nodal sampling: removing tails and ripples from SMOS Brightness Temperatures</a></li>      <li><a href="http://bec.icm.csic.es/comparison-of-smos-and-aquarius-tb/" title="Inter-comparison of SMOS and Aquarius observations">Inter-comparison of SMOS and Aquarius observations</a></li>      <li><a href="http://bec.icm.csic.es/merry-christmas-from-smos-bec/" title="Merry Christmas from SMOS BEC!">Merry Christmas from SMOS BEC!</a></li>      <li><a href="http://bec.icm.csic.es/can-smos-observe-mesoscale-eddies-in-the-algerian-basin/" title="Can SMOS observe mesoscale eddies in the Algerian basin?">Can SMOS observe mesoscale eddies in the Algerian basin?</a></li>      <li><a href="http://bec.icm.csic.es/six-years-of-the-new-smos-sss-maps-in-the-mediterranean-sea-now-available/" title="Six years of the new SMOS SSS maps in the Mediterranean Sea now available!">Six years of the new SMOS SSS maps in the Mediterranean Sea now available!</a></li>   </ul></aside><aside id="text-2" class="widget widget_text"><div class="widget-title">SMOS-BEC distribution list</div>   <div class="textwidget"><a href="https://listas.csic.es/cmima/wws/info/smos-bec-list" onclick="javascript:_gaq.push(['_trackEvent','outbound-widget','http://listas.csic.es']);" target="_blank"><img class="alignleft size-full" src="/wp-content/uploads/2012/11/smos-megafono.png" width=100 border=0></a>If you wish to be informed about new products and news, <a href="https://listas.csic.es/cmima/wws/info/smos-bec-list" onclick="javascript:_gaq.push(['_trackEvent','outbound-widget','http://listas.csic.es']);" target="_blank"> subscribe to our distribution list</a></div>  </aside>  <aside id="meta" class="widget widget_meta">   <div class="widget-title">Adds-on</div>   <ul>   <li><a href="http://bec.icm.csic.es/feed/" title="Syndicate this site using RSS 2.0">Entries <abbr title="Really Simple Syndication">RSS</abbr></a></li>      </ul>  </aside>  </div>   </div> <footer id="colophon" role="contentinfo">  <div id="site-generator">      Barcelona Expert Center, 2007 - 2018 <span class="sep"> &nbsp; |&nbsp; </span> CONTACT: <a class="texte" href="javascript:void" onclick="pos_corre('smos-bec','icm.csic','es')"><script type="text/javascript" language="javascript">// <![CDATA[don_corre('smos-bec','icm','csic.es')// ]]></script></a>  </div> </footer></div><script type='text/javascript'>/* <![CDATA[ */var sfw_ipwd_script = {"sfw_ajaxurl":"https:\/\/bec.icm.csic.es\/wp-admin\/admin-ajax.php"};/* ]]> */</script><script type='text/javascript' src='http://bec.icm.csic.es/wp-content/plugins/spam-free-wordpress/js/sfw-ipwd-nn.js?ver=1.9.2'></script></body></html>
Traceback (most recent call last):
  File "./bin/rheas", line 13, in <module>
    sys.exit(rheas.run())
  File "/rheas/src/rheas.py", line 89, in run
    update(dbname, config_filename)
  File "/rheas/src/rheas.py", line 68, in update
    mod.download(dbname, dt, bbox)
  File "/rheas/src/datasets/smos.py", line 48, in download
    f = netcdf.Dataset(url)
  File "netCDF4/_netCDF4.pyx", line 2111, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1731, in netCDF4._netCDF4._ensure_nc_success
IOError: [Errno -72] NetCDF: Malformed or inaccessible DAP DDS: 'http://rheas:rheasjpl@cp34-bec.cmima.csic.es/thredds/dodsC/NRTSM001D025A_ALL'

**Comment by kandread** [comment]
Unfortunately, the SMOS data provider's server is down for maintenance but according to them it should be up after May 28. Try it again in a couple of days, I'll try the same and hopefully their service will be up by then.

**Comment by kandread** [comment]
Just tested, server seems to be back up and ingestion is working. Closing but feel free to reopen if you're having issues.
